### ISSUE TITLE
migrate comments from Word Press

### ISSUE THREAD

**Issue by leftieFriele** [finn-no/tech.finn.no#1]

**Comment by leftieFriele** [comment]
Disqus has support for importing WP comments http://disqus.com/.
I don't know if there are better options available..

**Comment by Andersos** [comment]
@jarib What do you think about the commenting system? Should we use something like Disqus or go for something like https://github.com/mpalmer/jekyll-static-comments ?

**Comment by leftieFriele** [comment]
You could use GitHub issues for comments on posts. Easy and no walled
garden comment system stuff like Disqus.

**Comment by Andersos** [comment]
I like the idea. Lets do Github Issues

**Comment by michaelsembwever** [comment]
+1

**Comment by jarib** [comment]
@leftieFriele Any examples of blogs using Github issues for comments? 

Github issues can't be integrated into the blog AFAIK. So all visitors will have to come to Github to post or read comments. Easier for us perhaps, but not for our readers.

Disqus comments can be exported as XML. In addition they support multiple authentication options, which Github does not. How it is more of a walled garden than Github?

I'm not particularily for or against any specific solution, just trying to understand the arguments. 

Here are some Disqus alternatives:
- [livefyre](http://web.livefyre.com/)
- [IntenseDebate](http://intensedebate.com/)
- [Facebook Comments](https://developers.facebook.com/docs/plugins/comments)

**Comment by leftieFriele** [comment]
What I thought was that looking at current  comments they're from devs
who's very likely to have a GH account.

However, it could be a good idea to ditch comments and just use Twitter
mentions or similar.

**Comment by Andersos** [comment]
An example of how comments with the Github Issue system could work:
http://ivanzuzak.info/2012/11/18/the-web-engineers-online-toolbox.html

Code: 
https://github.com/izuzak/izuzak.github.com/blob/master/_layouts/post.html#L24-L65
or
https://github.com/qwertie/Loyc/blob/gh-pages/_includes/comments.html

It might be easier for the users if we have something like Disqus and it looks like there is good support for Disqus on Jekyll.
I'm against having Facebook comments.

**Comment by leftieFriele** [comment]
What I meant was having track back links. Where a comment would be someone
tweeting about it or sharing on Facebook. That way the conversations happen
in the social media and the blog just has references to those posts.

But lik u said Disqus has easy export from WP and use with Jekyll

**Comment by Andersos** [comment]
Disqus is now added and I imported the comments from Wordpress.
The 50 commnets will show up when we move to the tech.finn.no domain.
