### ISSUE TITLE
Authors

### ISSUE THREAD

**Issue by Andersos** [finn-no/tech.finn.no#14]
What do we want to happend when you click the author name (illustrated here)
![skjermbilde 2014-11-17 kl 12 00 26](https://cloud.githubusercontent.com/assets/288977/5068694/650c42ce-6e51-11e4-890f-b109c8f7e14c.png)

Do we want it to got to:
a. a mailto link with the email address to the author
b. a link to Tweet the author
c. an author page where multiple contact information can be displayed
d. other?
e. nothing 

Dose anyone of you have some input @leftieFriele, @michaelsembwever or @jarib 

Also update the old information in:
https://github.com/finn-no/tech.finn.no/blob/gh-pages/_data/authors.yml

**Comment by fmmr** [comment]
it seems like there is a mailto-link on author in posts today, but it's empty...

**Comment by Andersos** [comment]
Yes, it is because the data dose not include the emails. I didnt want to add the emails before people said it was okay to post their email. It should be added to this file https://github.com/finn-no/tech.finn.no/blob/gh-pages/_data/authors.yml

@michaelsembwever was talking about maybe having a author page like option c. Do you have any thoughts on how we should handle authors @fmmr ? =)

**Comment by fmmr** [comment]
Maybe something like this (including the icons for which we have info from authors.yml). It would then be up to the individual author which info to include. (I don't really care all that much except I think we should fix the broken link):

**Email providers in Norway**
November 21, 2014 by Anders Olsen Sandvik &lt;icon_twitter&gt;&lt;icon_github&gt;&lt;icon_email&gt;&lt;icon_email&gt;&lt;icon_about_me&gt;

It all started with a simple tweet:
...

**Comment by leftieFriele** [comment]
How about just using github profiles for link to the author? Then everyone
can decide what to do about it.

**Comment by Andersos** [comment]
If I understand you correct @leftieFriele  you are suggesting that the default behavior is to link to the users Github profile. If any author wants the "link" to go somewhere else they can decide for themselves and update that?

**Comment by leftieFriele** [comment]
Correct :)

**Comment by Andersos** [comment]
That sounds like a good solution. Anyone else have input on this?

**Comment by fmmr** [comment]
+1

**Comment by michaelsembwever** [comment]
+1

**Comment by Andersos** [comment]
So to do this we need to collect the Github names of the previous authors.
Just edit my post and write the name if you know.

Blog name (Github name)
- [x] mick (@michaelsembwever)
- [x] espen (@leftieFriele)
- [ ] tom post https://github.com/finn-no/tech.finn.no/blob/gh-pages/_posts/2011-10-14-make-real-estate-brokers-happy-with-hard-boiled-business-cards.markdown
- [x] vivek (@vivek1977)
- [x] mortenlj (@mortenlj)
- [x] roar (@roarjoh) https://github.com/finn-no/tech.finn.no/blob/gh-pages/_posts/2013-01-31-i-wish-i-knew-my-consumers-maven-reverse-dependency.markdown
- [x] Andersos (@Andersos)
- [x] firiaati (@firiaati)
- [x] fmr (@fmmr)
- [x] gregers (@gregersrygg)

If someone could help find the Github usernames for tom and roar that would be great.
![3570-that-would-be-great-bill-lumbergh-office-space-wallpaper-1024x768](https://cloud.githubusercontent.com/assets/288977/5183543/3b7dc332-74b0-11e4-8776-c0ab659a7bac.jpg)
