### ISSUE TITLE
Fix HTML-Proofer errors

### ISSUE THREAD

**Issue by Andersos** [finn-no/tech.finn.no#23]
Error:  HTML-Proofer found 436 failures! https://travis-ci.org/finn-no/tech.finn.no/builds/42864702
2014.12.03 436 Errors
2014.12.05 160 Errors

**Comment by Andersos** [comment]
Yey! Green build https://travis-ci.org/finn-no/tech.finn.no/builds/44330464

**Comment by fmmr** [comment]
high five!

**Comment by Andersos** [comment]
<3

**Comment by Andersos** [comment]
Then it broke again =( It is just part of checking #19

**Comment by Andersos** [comment]
Green again =)
