### ISSUE TITLE
Design update

### ISSUE THREAD

**Issue by Andersos** [finn-no/tech.finn.no#24]
Fix some of the design and make the blog look pretty.

**Comment by Andersos** [comment]
Close this when you feel you are done. Changes after that should be submitted as issues =)

**Comment by fmmr** [comment]
Thanks @antidecaf !  Looks and reads a lot better.

**Comment by Andersos** [comment]
I agree with @fmmr. It looks a lot better now @antidecaf  thanks! :tada:

**Comment by antidecaf** [comment]
Yay!

I'll close it for now but I'm sure I'll return at some point.

**Comment by Andersos** [comment]
:+1:
