### ISSUE TITLE
More space for content

### ISSUE THREAD

**Issue by Andersos** [finn-no/tech.finn.no#29]
So @michaelsembwever and I talked about giving more space for content on the post layout.
Especially code blocks have very little space.
We talked about improving that with the following:
- [x] Reduce font size in code blocks to 80%
- [x] Remove code block margins and indent
- [x] Remove the Post Archive from the post page (maybe move it under the content) to give more space to the content. 

Anyone have any thoughts on these changes?

**Comment by michaelsembwever** [comment]
even after i've polished the formatting the best i can for "the ultimate view", which is probably our article that has the most code snippets in it, and accounts for ~90% of the website's traffic, you can see that the code snippets still don't fit in.

**Comment by Andersos** [comment]
@michaelsembwever do you have any thoughts on this now? Do you think it is sufficiently solved so we can close it? Any other thoughts on how it looks now? =)

**Comment by michaelsembwever** [comment]
looks awesome now!

**Comment by Andersos** [comment]
:+1:
