### ISSUE TITLE
Post about mail

### ISSUE THREAD

**Issue by Andersos** [finn-no/tech.finn.no#3]
Relevant https://twitter.com/haavardb/status/441921895643226112

**Comment by Andersos** [comment]
<p>It all started with a simple tweet:</p><p>&lt;blockquote class="twitter-tweet" lang="en"&gt;&lt;p&gt;Er det noen som har noe norsk statistikk på bruk av e-post (gmail vs. outlook vs. online vs. yahoo osv)? F.eks &lt;a href="https://twitter.com/labs_finn_no"&gt;@labs_finn_no&lt;/a&gt; eller &lt;a href="https://twitter.com/NRKbeta"&gt;@NRKbeta&lt;/a&gt;?&lt;/p&gt;&amp;mdash; Håvard Bergersen (@haavardb) &lt;a href="https://twitter.com/haavardb/statuses/441921895643226112"&gt;March 7, 2014&lt;/a&gt;&lt;/blockquote&gt;<br />&lt;script async src="//platform.twitter.com/widgets.js" charset="utf-8"&gt;&lt;/script&gt;</p><p>"Does anyone have any Norwegian statistics on the use of email (Gmail vs. Outlook vs. Online vs.  Yahoo etc.)? Eg @labs_finn_no (https://twitter.com/labs_finn_no) or @nrkbeta (https://twitter.com/NRKbeta)."</p><p>I have access to the data so if this will help someone why not post it.<br />We have around 4 million mail addresses in a database. I made a table of some of the more popular e-mail domains or service providers.</p><p>hotmail.com 1106084 (28.056%)<br />gmail.com 599293 (15.201%)<br />online.no 444897 (11.285%)<br />live.no 96052 (2.436%)<br />yahoo.no 94029 (2.385%)<br />yahoo.com 75731 (1.921%)<br />hotmail.no 67602 (1.715%)<br />c2i.net 63859 (1.620%)<br />broadpark.no 48232 (1.223%)<br />frisurf.no 41768 (1.059%)<br />start.no 33409 (0.847%)<br />msn.com 29675 (0.753%)<br />lyse.net 23519 (0.597%)<br />getmail.no 19497 (0.495%)<br />chello.no 18485 (0.469%)<br />live.com 15014 (0.381%)<br />me.com 12344 (0.313%)<br />tele2.no 11781 (0.299%)<br />bluezone.no 10187 (0.258%)</p><p dir="ltr">This might be somewhat useful but a more interesting detail is what email client people are using.<br />This got me started on a future side project to include http://kb.mailchimp.com/article/can-mailchimp-tell-me-what-email-programs-or-webmail-service-my-subscribers/ </p><p>&nbsp;</p>

**Comment by joodland** [comment]
Just publish it. Maybe we should filter out old accounts or not SPID-verified accounts.

**Comment by nrkbeta** [comment]
Fun!
Is this something we can do a short piece on? Would filtering out of dead accounts be difficult?

**Comment by Andersos** [comment]
Im working on migrating the old posts: https://github.com/finn-no/tech.finn.no/issues/5
There is still some work left in https://github.com/finn-no/tech.finn.no/pull/9
Im planning on completing issue #5 this week and finish up this post as well.

I'm sure there would be no problem to do a short piece on this. If there is other information that would be useful let me know and I'll try to include it in the blogpost =)
