### ISSUE TITLE
Add missing posts

### ISSUE THREAD

**Issue by Andersos** [finn-no/tech.finn.no#5]
@michaelsembwever posts:
http://tech.finn.no/2014/10/27/log4j2-bringing-together-the-dependencies/
http://tech.finn.no/2014/07/01/log4j2-in-production-making-it-fly/
http://tech.finn.no/2012/08/06/foraging-in-the-landscape-of-big-data/
http://tech.finn.no/2012/07/25/the-ultimate-view-tiles-3/

@leftieFriele posts:
http://tech.finn.no/2014/06/06/conquering-the-kingdom-of-java-with-a-nodejs-trojan-horse/
http://tech.finn.no/2013/12/03/we-love-npm/
http://tech.finn.no/2013/11/29/low-fi-coffe-surveilence/

I will send a pull request per author for transferring the missing posts.

**Comment by michaelsembwever** [comment]
what about the two log4j2 posts ?

**Comment by Andersos** [comment]
All posts should be added now. If there are errors they can be reported in https://github.com/finn-no/tech.finn.no/issues/19
