### ISSUE TITLE
Use Spaden

### ISSUE THREAD

**Issue by jarib** [finn-no/tech.finn.no#6]
I think we should style the blog with Spaden instead of using the Poole CSS.

Thoughts?

**Comment by ivarconr** [comment]
+1 we should build on the FINN brand.

**Comment by leftieFriele** [comment]
I can stick Spaden on the blog no problem.

**Comment by Andersos** [comment]
+1

**Comment by Andersos** [comment]
We are getting some errors now. Maybe this is why the icons are not loading @leftieFriele Do you have any suggestions on how to solve this? =)

Font from origin 'http://finncdn.no' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://tech.finn.no' is therefore not allowed access. The response had HTTP status code 404. tech.finn.no/:1
Failed to load resource: the server responded with a status of 404 (Not Found) http://finncdn.no/bb/latest/css/spaden/styles/img/fonts/iconfont-01.woff
Font from origin 'http://finncdn.no' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://tech.finn.no' is therefore not allowed access. The response had HTTP status code 404. tech.finn.no/:1
Failed to load resource: the server responded with a status of 404 (Not Found) http://finncdn.no/bb/latest/css/spaden/styles/img/fonts/iconfont-01.ttf

**Comment by Andersos** [comment]
Yey @leftieFriele fixed the origin problem with https://github.com/finn-no/tech.finn.no/commit/63754827f77e8480325ee587b25104c52f77b2cb

**Comment by Andersos** [comment]
We are now using Spaden so closing this.
