### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by Andersos** [finn-no/tech.finn.no#7]
Before we were using Google Analytics on the Wordpress blog, with the id UA-45218426-6.
What should we use now?

**Comment by leftieFriele** [comment]
We should just run our own Piwik install and use that for things like this.
Or u can use analytics-js from finn-cdn.

**Comment by Andersos** [comment]
What is with the hate for Google Analytics? I'm for using GA. It works and it is easy to use. http://piwik.org/ although a great idea sounds like a lot of extra hassle to get working, monitoring and make sure that is is stable. 

There is a issue with user management with GA.

**Comment by leftieFriele** [comment]
no hating on GA, just company policies. we could just use the bundle on finncdn which tracks everything else.

**Comment by Andersos** [comment]
Espen just added the old GA id in https://github.com/finn-no/tech.finn.no/commit/c6357e7cd140ebae8fb4c630f9c946ea9f74d63a#diff-09179a8d5d4d14f990af950652a91667R6

It looks like it was okay to use GA for this blog. If this were to change please reopen this.
